{
  parserClass="ru.compscicenter.docide.language.parser.RDParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="RD"
  psiImplClassSuffix="Impl"
  psiPackage="ru.compscicenter.docide.language.psi"
  psiImplPackage="ru.compscicenter.docide.language.psi.impl"

  elementTypeHolderClass="ru.compscicenter.docide.language.psi.RDTypes"
  elementTypeClass="ru.compscicenter.docide.language.psi.RDElementType"
  tokenTypeClass="ru.compscicenter.docide.language.psi.RDTokenType"

  psiImplUtilClass="ru.compscicenter.docide.language.psi.impl.RDPsiImplUtil"
}

RDFile ::= item_*

private item_ ::= (property|tag|COMMENT|CRLF|report)

tag ::= AT KEY

report ::= EXEC column (SEP column)* (WHERE restriction (AND restriction)*)? RBR

property ::= AT KEY LBR VALUE RBR {methods=[getKey getValue]}

column ::= KEY AS VALUE {methods=[getKey getValue]}
restriction ::= KEY EQ VALUE {methods=[getKey getValue]}